### ISSUE TITLE
有些非常严重的问题

### ISSUE THREAD

**Issue by QQQOrange** [zxkmm/siyuan_doctree_compress#4]
打开子文档的按钮位置发生了改变，并且是鼠标指上去之后改变的
再就是换行显示的话，如果一行标题字比较多，那么鼠标从这一文档往下移动，不会指向下一个文档，而是会跳过几个文档

**Comment by zxkmm** [comment]
1. 请问是哪个功能存在这个问题呢？有没有录屏演示？
2. 换行那个我没有找到解决方案，建议不要启用这个功能

**Comment by zxkmm** [comment]
这个是流动布局的特性，启用后鼠标悬浮到的项目会自动流动到没有缩进的位置
如果不需要这个功能，可以到插件设置把流动布局的两个开关关掉

**Comment by QQQOrange** [comment]
> 这个是流动布局的特性，启用后鼠标悬浮到的项目会自动流动到没有缩进的位置 如果不需要这个功能，可以到插件设置把流动布局的两个开关关掉

把流动布局关掉就好了，大佬牛逼

**Comment by zxkmm** [comment]
@QQQOrange 谢谢您，解决了就好。   
启用流动布局后，第一列内容永远是子文档树开关，第二列永远是文档图标，第三列永远是文档名，第四列永远是上下文菜单按钮，第五列永远是添加子文档按钮。这个功能如果习惯的话还是挺方便的，可以解决很多问题。只是需要习惯一下才会用

**Comment by QQQOrange** [comment]
> @QQQOrange 谢谢您，解决了就好。 启用流动布局后，第一列内容永远是子文档树开关，第二列永远是文档图标，第三列永远是文档名，第四列永远是上下文菜单按钮，第五列永远是添加子文档按钮。这个功能如果习惯的话还是挺方便的，可以解决很多问题，还可以做到盲操作，不用去找图标的位置。只是需要习惯一下才会用

好嘞 我试着熟悉一下 笔芯

**Comment by zxkmm** [comment]
谢谢,那我就先关闭issue了。如果方便的话希望可以给我点一个免费的github星星，感谢！
![image](https://github.com/zxkmm/siyuan_doctree_compress/assets/24917424/03d22054-932a-4ca0-b470-53f4adab01aa)

**Comment by QQQOrange** [comment]
> 谢谢,那我就先关闭issue了。如果方便的话希望可以给我点一个免费的github星星，感谢！ ![image](https://private-user-images.githubusercontent.com/24917424/297021681-03d22054-932a-4ca0-b470-53f4adab01aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MDQxOTAsIm5iZiI6MTcwNTQwMzg5MCwicGF0aCI6Ii8yNDkxNzQyNC8yOTcwMjE2ODEtMDNkMjIwNTQtOTMyYS00Y2EwLWI0NzAtNTNmNGFkYWIwMWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDExMTgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyMzZiNGRjN2YwMzFkOGY0YWQwYTk3ZDEwNzNiNjQyYmU2OWYxOWI3OGNlODFmOTI1OThmZmZiMDY3YTA2OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PW3DlzVhd-IIQQ3lwcseVjQdf5qZyQLY2bowTOW03NU)

妥妥的 笔芯
